name: Publish on GitHub

on: [workflow_dispatch]

env:
  MOD_VERSION: 1.1.0
  MINECRAFT_VERSION: 1.21.1
  JAVA_VERSION: 21
  VERSION: ${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}
  RELEASE_NAME: VillagerPickup ${{ env.MOD_VERSION }} for Minecraft ${{ env.MINECRAFT_VERSION }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (GitHub)
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          tag_name: ${{ env.VERSION }}
          name: ${{ env.RELEASE_NAME }}
