name: Publish on GitHub

on: [workflow_dispatch]

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17
  VERSION: 1.0.0+1.20.4
  RELEASE_NAME: VillagerPickup 1.0.0 for Minecraft 1.20.4

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (GitHub)
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          tag_name: ${{ env.VERSION }}
          name: ${{ env.RELEASE_NAME }}